# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build Client with Maven
      run: mvn -B package --file pom.xml -P client

    - name: Rename Client Artifact
      run: mv target/TypeRacerClient-jar-with-dependencies.jar target/TypeRacerClient.jar

    - name: Upload Client Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TypeRacerClient
        path: target/TypeRacerClient.jar

    - name: Build Server with Maven
      run: mvn -B package --file pom.xml -P server

    - name: Rename Server Artifact
      run: mv target/TypeRacerServer-jar-with-dependencies.jar target/TypeRacerServer.jar

    - name: Upload Server Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TypeRacerServer
        path: target/TypeRacerServer.jar
